required = [
  # "k8s.io/apimachinery/pkg/util/sets/types",
  "k8s.io/code-generator/cmd/deepcopy-gen",
  "k8s.io/code-generator/cmd/client-gen",
  "k8s.io/code-generator/cmd/defaulter-gen",
  "k8s.io/code-generator/cmd/lister-gen",
  "k8s.io/code-generator/cmd/informer-gen",
  "k8s.io/code-generator/cmd/openapi-gen",
]

# [[override]]
#   name = "gopkg.in/yaml.v2"
#   version = "v2.2.1"

[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.12.4"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.12.4"

[[override]]
  name = "k8s.io/code-generator"
  version = "kubernetes-1.12.4"

[[override]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.12.4"

[prune]
  go-tests = true
  unused-packages = true
  non-go = true

[[prune.project]]
  name = "k8s.io/code-generator"
  unused-packages = false
  non-go = false