// Copyright © 2018 the Kudzu contributors.
// Licensed under the Apache License, Version 2.0; see the NOTICE file.

// Code generated by lister. DO NOT EDIT.

package v1alpha1

// APIListerExpansion allows custom methods to be added to
// APILister.
type APIListerExpansion interface{}
