// Copyright © 2018 the Kudzu contributors.
// Licensed under the Apache License, Version 2.0; see the NOTICE file.

// Code generated by informer. DO NOT EDIT.

package v1alpha1

import (
	internalinterfaces "kudzu.sh/api/client/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// APIs returns a APIInformer.
	APIs() APIInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// APIs returns a APIInformer.
func (v *version) APIs() APIInformer {
	return &aPIInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}
