// Copyright © 2018 the Kudzu contributors.
// Licensed under the Apache License, Version 2.0; see the NOTICE file.

// Code generated by client. DO NOT EDIT.

package fake

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1alpha1 "kudzu.sh/api/kudzu/v1alpha1"
)

// FakeAPIs implements APIInterface
type FakeAPIs struct {
	Fake *FakeKudzuV1alpha1
}

var apisResource = schema.GroupVersionResource{Group: "kudzu.sh", Version: "v1alpha1", Resource: "apis"}

var apisKind = schema.GroupVersionKind{Group: "kudzu.sh", Version: "v1alpha1", Kind: "API"}

// Get takes name of the aPI, and returns the corresponding aPI object, and an error if there is any.
func (c *FakeAPIs) Get(name string, options v1.GetOptions) (result *v1alpha1.API, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(apisResource, name), &v1alpha1.API{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.API), err
}

// List takes label and field selectors, and returns the list of APIs that match those selectors.
func (c *FakeAPIs) List(opts v1.ListOptions) (result *v1alpha1.APIList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(apisResource, apisKind, opts), &v1alpha1.APIList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.APIList{ListMeta: obj.(*v1alpha1.APIList).ListMeta}
	for _, item := range obj.(*v1alpha1.APIList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested aPIs.
func (c *FakeAPIs) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(apisResource, opts))
}

// Create takes the representation of a aPI and creates it.  Returns the server's representation of the aPI, and an error, if there is any.
func (c *FakeAPIs) Create(aPI *v1alpha1.API) (result *v1alpha1.API, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(apisResource, aPI), &v1alpha1.API{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.API), err
}

// Update takes the representation of a aPI and updates it. Returns the server's representation of the aPI, and an error, if there is any.
func (c *FakeAPIs) Update(aPI *v1alpha1.API) (result *v1alpha1.API, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(apisResource, aPI), &v1alpha1.API{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.API), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeAPIs) UpdateStatus(aPI *v1alpha1.API) (*v1alpha1.API, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(apisResource, "status", aPI), &v1alpha1.API{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.API), err
}

// Delete takes name of the aPI and deletes it. Returns an error if one occurs.
func (c *FakeAPIs) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(apisResource, name), &v1alpha1.API{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeAPIs) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(apisResource, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.APIList{})
	return err
}

// Patch applies the patch and returns the patched aPI.
func (c *FakeAPIs) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.API, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(apisResource, name, data, subresources...), &v1alpha1.API{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.API), err
}
