// Copyright © 2018 the Kudzu contributors.
// Licensed under the Apache License, Version 2.0; see the NOTICE file.

// Code generated by client. DO NOT EDIT.

package fake

import (
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
	v1alpha1 "kudzu.sh/api/client/typed/kudzu/v1alpha1"
)

type FakeKudzuV1alpha1 struct {
	*testing.Fake
}

func (c *FakeKudzuV1alpha1) APIs() v1alpha1.APIInterface {
	return &FakeAPIs{c}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeKudzuV1alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
