// Copyright © 2018 the Kudzu contributors.
// Licensed under the Apache License, Version 2.0; see the NOTICE file.

// Code generated by client. DO NOT EDIT.

package v1alpha1

import (
	serializer "k8s.io/apimachinery/pkg/runtime/serializer"
	rest "k8s.io/client-go/rest"
	"kudzu.sh/api/client/scheme"
	v1alpha1 "kudzu.sh/api/kudzu/v1alpha1"
)

type KudzuV1alpha1Interface interface {
	RESTClient() rest.Interface
	APIsGetter
}

// KudzuV1alpha1Client is used to interact with features provided by the kudzu.sh group.
type KudzuV1alpha1Client struct {
	restClient rest.Interface
}

func (c *KudzuV1alpha1Client) APIs() APIInterface {
	return newAPIs(c)
}

// NewForConfig creates a new KudzuV1alpha1Client for the given config.
func NewForConfig(c *rest.Config) (*KudzuV1alpha1Client, error) {
	config := *c
	if err := setConfigDefaults(&config); err != nil {
		return nil, err
	}
	client, err := rest.RESTClientFor(&config)
	if err != nil {
		return nil, err
	}
	return &KudzuV1alpha1Client{client}, nil
}

// NewForConfigOrDie creates a new KudzuV1alpha1Client for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *KudzuV1alpha1Client {
	client, err := NewForConfig(c)
	if err != nil {
		panic(err)
	}
	return client
}

// New creates a new KudzuV1alpha1Client for the given RESTClient.
func New(c rest.Interface) *KudzuV1alpha1Client {
	return &KudzuV1alpha1Client{c}
}

func setConfigDefaults(config *rest.Config) error {
	gv := v1alpha1.SchemeGroupVersion
	config.GroupVersion = &gv
	config.APIPath = "/apis"
	config.NegotiatedSerializer = serializer.DirectCodecFactory{CodecFactory: scheme.Codecs}

	if config.UserAgent == "" {
		config.UserAgent = rest.DefaultKubernetesUserAgent()
	}

	return nil
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *KudzuV1alpha1Client) RESTClient() rest.Interface {
	if c == nil {
		return nil
	}
	return c.restClient
}
